
services:
  veiculoverde-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veiculoverde-api
    ports:
      - "80:8080"
      - "443:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=esg_cidades;Username=esguser;Password=esgpassword
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    networks:
      - esg_network

  db:
    image: postgres:14-alpine
    container_name: esg-db
    restart: always
    environment:
      - POSTGRES_USER=esguser
      - POSTGRES_PASSWORD=esgpassword
      - POSTGRES_DB=esg_cidades
    ports:
      - "5432:5432"
    volumes:
      - esg_db_data:/var/lib/postgresql/data/
    networks:
      - esg_network

networks:
  esg_network:
    driver: bridge

volumes:
  esg_db_data:
    driver: local
