// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeiculoVerde.Infrastructure.Data;

#nullable disable

namespace VeiculoVerde.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251017053336_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeiculoVerde.Domain.Entities.ImpactoAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("EconomiaCombustivelTotalLitros")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<int>("NumeroSubstituicoes")
                        .HasColumnType("integer");

                    b.Property<decimal>("ReducaoCO2TotalKg")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ImpactosAmbientais");
                });

            modelBuilder.Entity("VeiculoVerde.Domain.Entities.VeiculoSubstituido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFabricacaoVeiculoCombustao")
                        .HasColumnType("integer");

                    b.Property<decimal>("AutonomiaVeiculoSubstitutoKm")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ConsumoCombustivelAnteriorKmPorLitro")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DataSubstituicao")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("EmissaoCO2Anterior")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EmissaoCO2Nova")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("MarcaVeiculoCombustao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarcaVeiculoSubstituto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModeloVeiculoCombustao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModeloVeiculoSubstituto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlacaVeiculoCombustao")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TipoVeiculoSubstituto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VeiculosSubstituidos");
                });
#pragma warning restore 612, 618
        }
    }
}
